
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Arrange generated by hbm2java
 */
public class Arrange implements java.io.Serializable {

	private int arrangeid;
	/**
	 * 1是岗前培训，2是律协活动
	 */
	private byte arrangetype;
	private String title;
	private String content;
	private String arrangend;
	private Short maxpersons;
	private Timestamp createtime;
	private long createuser;
	private String remarks;
	
	private int baomingrenshu;
	private int shiwusuo;
	private boolean canbaoming;
	
	private Set<Arrangesignup> arrangesignups = new HashSet<Arrangesignup>(0);

	public Arrange() {
	}

	public Arrange(byte arrangetype, String title, Timestamp createtime, long createuser) {
		this.arrangetype = arrangetype;
		this.title = title;
		this.createtime = createtime;
		this.createuser = createuser;
	}

	public Arrange(byte arrangetype, String title, String content, String arrangend, Short maxpersons, Timestamp createtime, long createuser,
			String remarks, Set<Arrangesignup> arrangesignups) {
		this.arrangetype = arrangetype;
		this.title = title;
		this.content = content;
		this.arrangend = arrangend;
		this.maxpersons = maxpersons;
		this.createtime = createtime;
		this.createuser = createuser;
		this.remarks = remarks;
		this.arrangesignups = arrangesignups;
	}

	public int getArrangeid() {
		return this.arrangeid;
	}

	public void setArrangeid(int arrangeid) {
		this.arrangeid = arrangeid;
	}

	public byte getArrangetype() {
		return this.arrangetype;
	}

	public void setArrangetype(byte arrangetype) {
		this.arrangetype = arrangetype;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getArrangend() {
		return this.arrangend;
	}

	public void setArrangend(String arrangend) {
		this.arrangend = arrangend;
	}

	public Short getMaxpersons() {
		return this.maxpersons;
	}

	public void setMaxpersons(Short maxpersons) {
		this.maxpersons = maxpersons;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public long getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(long createuser) {
		this.createuser = createuser;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Set<Arrangesignup> getArrangesignups() {
		return this.arrangesignups;
	}

	public void setArrangesignups(Set<Arrangesignup> arrangesignups) {
		this.arrangesignups = arrangesignups;
	}

	/**
	 * @return the baomingrenshu
	 */
	public int getBaomingrenshu() {
		return baomingrenshu;
	}

	/**
	 * @param baomingrenshu the baomingrenshu to set
	 */
	public void setBaomingrenshu(int baomingrenshu) {
		this.baomingrenshu = baomingrenshu;
	}

	/**
	 * @return the shiwusuo
	 */
	public int getShiwusuo() {
		return shiwusuo;
	}

	/**
	 * @param shiwusuo the shiwusuo to set
	 */
	public void setShiwusuo(int shiwusuo) {
		this.shiwusuo = shiwusuo;
	}

	/**
	 * @return the canbaoming
	 */
	public boolean isCanbaoming() {
		return canbaoming;
	}

	/**
	 * @param canbaoming the canbaoming to set
	 */
	public void setCanbaoming(boolean canbaoming) {
		this.canbaoming = canbaoming;
	}

}
