
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1
import java.sql.Timestamp;

/**
 * Forum generated by hbm2java
 */
public class Forum implements java.io.Serializable {

	private int forumid;
	private String title;
	private String createuser;
	private Timestamp createtime;
	private Boolean ismain;
	private Boolean delflag;
	private Timestamp lastupdate;
	private Integer mainforum;
	private int replycount;
	private String forumcontent;




	/**
	 * @return the forumcontent
	 */
	public String getForumcontent() {
		return forumcontent;
	}


	/**
	 * @param forumcontent the forumcontent to set
	 */
	public void setForumcontent(String forumcontent) {
		this.forumcontent = forumcontent;
	}


	public Forum() {
	}


	public int getForumid() {
		return this.forumid;
	}

	public void setForumid(int forumid) {
		this.forumid = forumid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public Boolean isIsmain() {
		return this.ismain;
	}

	public void setIsmain(Boolean ismain) {
		this.ismain = ismain;
	}

	public Timestamp getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Timestamp lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Integer getMainforum() {
		return this.mainforum;
	}

	public void setMainforum(Integer mainforum) {
		this.mainforum = mainforum;
	}

	public int getReplycount() {
		return this.replycount;
	}

	public void setReplycount(int replycount) {
		this.replycount = replycount;
	}


	/**
	 * @return the delflag
	 */
	public Boolean getDelflag() {
		return delflag;
	}


	/**
	 * @param delflag the delflag to set
	 */
	public void setDelflag(Boolean delflag) {
		this.delflag = delflag;
	}


	/**
	 * @return the ismain
	 */
	public Boolean getIsmain() {
		return ismain;
	}

}
