
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;

import com.changpeng.models.system.SysUser;

/**
 * Lawyerlessonxf generated by hbm2java
 */
public class Lawyerlessonxf implements java.io.Serializable {

	private int xfid;
	private SysUser lawer;
	private Integer lessonid;
	private Integer wareid;
	private Integer budengid;
	private String title;
	/**
	 * 现场培训，在线视频，文本课件，补登积分。如果是积分补登的话，title不为空
	 */
	private String learnmode;
	private String pxdate;
	private Float pxreqminutes;
	private Float pxminutes;
	private Float pxxf;
	private String remarks;
	
	private Timestamp lastupdate;
	private int theyear;
	private int islastyear;

	public int getTheyear() {
		return theyear;
	}



	public void setTheyear(int theyear) {
		this.theyear = theyear;
	}



	public int getIslastyear() {
		return islastyear;
	}



	public void setIslastyear(int islastyear) {
		this.islastyear = islastyear;
	}



	/**
	 * @return the remarks
	 */
	public String getRemarks() {
		return remarks;
	}



	/**
	 * @param remarks the remarks to set
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}



	public Lawyerlessonxf() {
	}

	

	public int getXfid() {
		return this.xfid;
	}

	public void setXfid(int xfid) {
		this.xfid = xfid;
	}

	public SysUser getLawer() {
		return this.lawer;
	}

	public void setLawer(SysUser lawer) {
		this.lawer = lawer;
	}

	public Integer getLessonid() {
		return this.lessonid;
	}

	public void setLessonid(Integer lessonid) {
		this.lessonid = lessonid;
	}

	public String getLearnmode() {
		return this.learnmode;
	}

	public void setLearnmode(String learnmode) {
		this.learnmode = learnmode;
	}

	public String getPxdate() {
		return this.pxdate;
	}

	public void setPxdate(String pxdate) {
		this.pxdate = pxdate;
	}

	public Float getPxreqminutes() {
		return this.pxreqminutes;
	}

	public void setPxreqminutes(Float pxreqminutes) {
		this.pxreqminutes = pxreqminutes;
	}

	public Float getPxminutes() {
		return this.pxminutes;
	}

	public void setPxminutes(Float pxminutes) {
		this.pxminutes = pxminutes;
	}

	public Float getPxxf() {
		return this.pxxf;
	}

	public void setPxxf(Float pxxf) {
		this.pxxf = pxxf;
	}



	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}



	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}



	/**
	 * @return the budengid
	 */
	public Integer getBudengid() {
		return budengid;
	}



	/**
	 * @param budengid the budengid to set
	 */
	public void setBudengid(Integer budengid) {
		this.budengid = budengid;
	}



	/**
	 * @return the lastupdate
	 */
	public Timestamp getLastupdate() {
		return lastupdate;
	}



	/**
	 * @param lastupdate the lastupdate to set
	 */
	public void setLastupdate(Timestamp lastupdate) {
		this.lastupdate = lastupdate;
	}
	
	private boolean ismanfen;
	public void setIsmanfen(boolean ismanfen){
		this.ismanfen=ismanfen;
	}
	public boolean getIsmanfen(){
		return this.ismanfen;
	}



	public Integer getWareid() {
		return wareid;
	}



	public void setWareid(Integer wareid) {
		this.wareid = wareid;
	}

}
