
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;
import java.text.DateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lessons generated by hbm2java
 */
public class Lessons implements java.io.Serializable {

	private int lessonid;
	private String title;
	private Byte lessonstate;
	private String teachers;
	private Byte lessontype;
	private Float xuefen;
	private String lessondate;
	private String lessonend;
	private String lessonaddress;
	private String lessoncontent;
	private Float kaoqinshichang;
	private Boolean isalert;
	private Short maxpersons;
	private Float notexistfen;
	private String onlinefile;
	private String fenshuoff;
	private long createuser;
	private Timestamp createtime;
	private Boolean isbixiu;
	private String minrate;
	private Short baomingshu;
	private Set<Lessonscore> lessonscores = new HashSet<Lessonscore>(0);
	private Set<Lessonbaoming> lessonbaomings = new HashSet<Lessonbaoming>(0);
	private Set<Lessonreply> lessonreplys = new HashSet<Lessonreply>(0);
	
	private String attach; //附件

//	private Set<Lawyerlessonxf> lessonxf = new HashSet<Lawyerlessonxf>(0);

	public Lessons() {
	}

	public Lessons(String title, long createuser, Timestamp createtime, Boolean isbixiu) {
		this.title = title;
		this.createuser = createuser;
		this.createtime = createtime;
		this.isbixiu = isbixiu;
	}

	public Lessons(String title, Byte lessonstate, String teachers, Byte lessontype, Float xuefen, String lessondate, String lessonend,
			String lessonaddress, String lessoncontent, Float kaoqinshichang, Boolean isalert, Short maxpersons, Float notexistfen,
			String onlinefile, String fenshuoff, long createuser, Timestamp createtime, Boolean isbixiu, String minrate, Short baomingshu,
			Set<Lessonscore> lessonscores, Set<Lessonbaoming> lessonbaomings) {
		this.title = title;
		this.lessonstate = lessonstate;
		this.teachers = teachers;
		this.lessontype = lessontype;
		this.xuefen = xuefen;
		this.lessondate = lessondate;
		this.lessonend = lessonend;
		this.lessonaddress = lessonaddress;
		this.lessoncontent = lessoncontent;
		this.kaoqinshichang = kaoqinshichang;
		this.isalert = isalert;
		this.maxpersons = maxpersons;
		this.notexistfen = notexistfen;
		this.onlinefile = onlinefile;
		this.fenshuoff = fenshuoff;
		this.createuser = createuser;
		this.createtime = createtime;
		this.isbixiu = isbixiu;
		this.minrate = minrate;
		this.baomingshu = baomingshu;
		this.lessonscores = lessonscores;
		this.lessonbaomings = lessonbaomings;
	}

	public int getLessonid() {
		return this.lessonid;
	}

	public void setLessonid(int lessonid) {
		this.lessonid = lessonid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Byte getLessonstate() {
		return this.lessonstate;
	}

	public void setLessonstate(Byte lessonstate) {
		this.lessonstate = lessonstate;
	}

	public String getTeachers() {
		return this.teachers;
	}

	public void setTeachers(String teachers) {
		this.teachers = teachers;
	}

	public Byte getLessontype() {
		return this.lessontype;
	}

	public void setLessontype(Byte lessontype) {
		this.lessontype = lessontype;
	}

	public Float getXuefen() {
		return this.xuefen;
	}

	public void setXuefen(Float xuefen) {
		this.xuefen = xuefen;
	}

	public String getLessondate() {
		return this.lessondate;
	}

	public void setLessondate(String lessondate) {
		this.lessondate = lessondate;
	}

	public String getLessonend() {
		return this.lessonend;
	}

	public void setLessonend(String lessonend) {
		this.lessonend = lessonend;
	}

	public String getLessonaddress() {
		return this.lessonaddress;
	}

	public void setLessonaddress(String lessonaddress) {
		this.lessonaddress = lessonaddress;
	}

	public String getLessoncontent() {
		return this.lessoncontent;
	}

	public void setLessoncontent(String lessoncontent) {
		this.lessoncontent = lessoncontent;
	}

	public Float getKaoqinshichang() {
		return this.kaoqinshichang;
	}

	public void setKaoqinshichang(Float kaoqinshichang) {
		this.kaoqinshichang = kaoqinshichang;
	}

	public Boolean getIsalert() {
		return this.isalert;
	}

	public void setIsalert(Boolean isalert) {
		this.isalert = isalert;
	}

	public Short getMaxpersons() {
		return this.maxpersons;
	}

	public void setMaxpersons(Short maxpersons) {
		this.maxpersons = maxpersons;
	}

	public Float getNotexistfen() {
		return this.notexistfen;
	}

	public void setNotexistfen(Float notexistfen) {
		this.notexistfen = notexistfen;
	}

	public String getOnlinefile() {
		return this.onlinefile;
	}

	public void setOnlinefile(String onlinefile) {
		this.onlinefile = onlinefile;
	}

	public String getFenshuoff() {
		return this.fenshuoff;
	}

	public void setFenshuoff(String fenshuoff) {
		this.fenshuoff = fenshuoff;
	}

	public long getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(long createuser) {
		this.createuser = createuser;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public Boolean getIsbixiu() {
		return this.isbixiu;
	}

	public void setIsbixiu(Boolean isbixiu) {
		this.isbixiu = isbixiu;
	}

	public String getMinrate() {
		return this.minrate;
	}

	public void setMinrate(String minrate) {
		this.minrate = minrate;
	}

	public Short getBaomingshu() {
		return this.baomingshu;
	}

	public void setBaomingshu(Short baomingshu) {
		this.baomingshu = baomingshu;
	}

	public Set<Lessonscore> getLessonscores() {
		return this.lessonscores;
	}

	public void setLessonscores(Set<Lessonscore> lessonscores) {
		this.lessonscores = lessonscores;
	}

	public Set<Lessonbaoming> getLessonbaomings() {
		return this.lessonbaomings;
	}

	public void setLessonbaomings(Set<Lessonbaoming> lessonbaomings) {
		this.lessonbaomings = lessonbaomings;
	}

//	/**
//	 * @return the lessonxf
//	 */
//	public Set<Lawyerlessonxf> getLessonxf() {
//		return lessonxf;
//	}
//
//	/**
//	 * @param lessonxf
//	 *            the lessonxf to set
//	 */
//	public void setLessonxf(Set<Lawyerlessonxf> lessonxf) {
//		this.lessonxf = lessonxf;
//	}

	private static final DateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");

	// 1这个人已经报名了2过了报名时间了
	private int baominguser;
	private boolean issetbaominguser;

	public void setBaominguser(int baominguser) {
		issetbaominguser = true;
		this.baominguser = baominguser;
	}

	public int getBaominguser() {
		if (!issetbaominguser) {
			try {
				Date now = new Date();
				Date dt = df.parse(this.lessondate);
				if (now.after(dt)) {//如果现在在报名时间后，则认为过了报名时间了
					baominguser = 2;
				}
			}
			catch (Exception e) {

			}
		}
		return baominguser;
	}
	
	private Lawyerlessonxf userlessonxf;

	/**
	 * @return the userlessonxf
	 */
	public Lawyerlessonxf getUserlessonxf() {
		return userlessonxf;
	}

	/**
	 * @param userlessonxf the userlessonxf to set
	 */
	public void setUserlessonxf(Lawyerlessonxf userlessonxf) {
		this.userlessonxf = userlessonxf;
	}

	public Set<Lessonreply> getLessonreplys() {
		return lessonreplys;
	}

	public void setLessonreplys(Set<Lessonreply> lessonreplys) {
		this.lessonreplys = lessonreplys;
	}

	public String getAttach() {
		return attach;
	}

	public void setAttach(String attach) {
		this.attach = attach;
	}
	
}