
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Diaochawenti generated by hbm2java
 */
public class Diaochawenti implements java.io.Serializable {

	private int wentiid;
	private Diaocha diaocha;
	private String title;
	private int wentileixing;
	//private String options;
	private Boolean isbixu;
	//private Boolean islogic;
	private Timestamp createtime;
	private String createuser;
	private String remarks;
	private Set<Diaochaoption> diaochaoptions = new HashSet<Diaochaoption>(0);
	
	private Set<Diaochareply> diaochareplys = new HashSet<Diaochareply>(0);
	
	private Diaochatype diaochatype;
	private int listorder;
	public int getListorder() {
		return listorder;
	}

	public void setListorder(int listorder) {
		this.listorder = listorder;
	}

	public Diaochatype getDiaochatype() {
		return diaochatype;
	}

	public void setDiaochatype(Diaochatype diaochatype) {
		this.diaochatype = diaochatype;
	}

	public Diaochawenti() {
	}

	public Diaochawenti(int wentiid, Diaocha diaocha, String title, int wentileixing,  Boolean isbixu, 
			Timestamp createtime, String createuser, String remarks) {
		this.wentiid = wentiid;
		this.diaocha = diaocha;
		this.title = title;
		this.wentileixing = wentileixing;
		//this.options = options;
		this.isbixu = isbixu;
		//this.islogic = islogic;
		this.createtime = createtime;
		this.createuser = createuser;
		this.remarks = remarks;
	}

	public Diaochawenti(int wentiid, Diaocha diaocha, String title, int wentileixing, Boolean isbixu, 
			Timestamp createtime, String createuser, String remarks, Set<Diaochaoption> diaochaoptions) {
		this.wentiid = wentiid;
		this.diaocha = diaocha;
		this.title = title;
		this.wentileixing = wentileixing;
		//this.options = options;
		this.isbixu = isbixu;
		//this.islogic = islogic;
		this.createtime = createtime;
		this.createuser = createuser;
		this.remarks = remarks;
		this.diaochaoptions = diaochaoptions;
	}

	public int getWentiid() {
		return this.wentiid;
	}

	public void setWentiid(int wentiid) {
		this.wentiid = wentiid;
	}

	public Diaocha getDiaocha() {
		return this.diaocha;
	}

	public void setDiaocha(Diaocha diaocha) {
		this.diaocha = diaocha;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getWentileixing() {
		return this.wentileixing;
	}

	public void setWentileixing(int wentileixing) {
		this.wentileixing = wentileixing;
	}

	/*public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}*/

	public Boolean getIsbixu() {
		return this.isbixu;
	}

	public void setIsbixu(Boolean isbixu) {
		this.isbixu = isbixu;
	}

	/*public Boolean getIslogic() {
		return this.islogic;
	}

	public void setIslogic(Boolean islogic) {
		this.islogic = islogic;
	}*/

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public String getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Set<Diaochaoption> getDiaochaoptions() {
		return this.diaochaoptions;
	}

	public void setDiaochaoptions(Set<Diaochaoption> diaochaoptions) {
		this.diaochaoptions = diaochaoptions;
	}

	public Set<Diaochareply> getDiaochareplys() {
		return diaochareplys;
	}

	public void setDiaochareplys(Set<Diaochareply> diaochareplys) {
		this.diaochareplys = diaochareplys;
	}

}
