
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Diaocha generated by hbm2java
 */
public class Diaocha implements java.io.Serializable {

	private int diaochaid;
	private String title;
	private String createuser;
	private Timestamp createtime;
	private String shuoming;
	private int state;
	private int replycount;
	private Set<Diaochawenti> diaochawentis = new HashSet<Diaochawenti>(0);
	
	private Set<Diaochatype> diaochatypes = new HashSet<Diaochatype>(0);
	
	public Diaocha() {
	}

	public Diaocha(int diaochaid, String title, String createuser, Timestamp createtime, String shuoming, 
			int state,int replycount) {
		this.diaochaid = diaochaid;
		this.title = title;
		this.createuser = createuser;
		this.createtime = createtime;
		this.shuoming = shuoming;
		this.state=state;
		this.replycount = replycount;
	}

	public Diaocha(int diaochaid, String title, String createuser, Timestamp createtime, String shuoming, int state,
			int replycount, Set<Diaochawenti> diaochawentis) {
		this.diaochaid = diaochaid;
		this.title = title;
		this.createuser = createuser;
		this.createtime = createtime;
		this.shuoming = shuoming;
		this.state=state;
		this.replycount = replycount;
		this.diaochawentis = diaochawentis;
	}

	public int getDiaochaid() {
		return this.diaochaid;
	}

	public void setDiaochaid(int diaochaid) {
		this.diaochaid = diaochaid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public String getShuoming() {
		return this.shuoming;
	}

	public void setShuoming(String shuoming) {
		this.shuoming = shuoming;
	}


	public int getReplycount() {
		return this.replycount;
	}

	public void setReplycount(int replycount) {
		this.replycount = replycount;
	}

	public Set<Diaochawenti> getDiaochawentis() {
		return this.diaochawentis;
	}

	public void setDiaochawentis(Set<Diaochawenti> diaochawentis) {
		this.diaochawentis = diaochawentis;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Set<Diaochatype> getDiaochatypes() {
		return diaochatypes;
	}

	public void setDiaochatypes(Set<Diaochatype> diaochatypes) {
		this.diaochatypes = diaochatypes;
	}

}
