package com.changpeng.core.model;

// Generated 2007-10-10 17:32:03 by Hibernate Tools 3.2.0.b9


/**
 * TwatWait generated by hbm2java
 */
public class CorePartner implements java.io.Serializable {

	private int id;
	private String name;
	private String logo;
	private String url;
	private String description;
	private int status;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getLogo() {
		return logo;
	}
	public void setLogo(String logo) {
		this.logo = logo;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	

}
