package com.changpeng.core.model;

// Generated 2007-10-10 17:32:03 by Hibernate Tools 3.2.0.b9


/**
 * TwatWait generated by hbm2java
 */
public class SysParameter implements java.io.Serializable {

	private String paramname;
	private String paramvalue;
	private int typeid;
	public int getTypeid() {
		return typeid;
	}
	public void setTypeid(int typeid) {
		this.typeid = typeid;
	}
	public String getParamname() {
		return paramname;
	}
	public void setParamname(String paramname) {
		this.paramname = paramname;
	}
	public String getParamvalue() {
		return paramvalue;
	}
	public void setParamvalue(String paramvalue) {
		this.paramvalue = paramvalue;
	}



}
