package com.uu800.admin.base.entity;

import java.util.HashSet;
import java.util.Set;

import com.uu800.webbase.util.Tree;

/**
 * TsysAreaCode generated by MyEclipse Persistence Tools
 */

public class TsysAreaCode implements java.io.Serializable
{

	// Fields

	private String areacode;
	private String areaname;
	private String areadesc;
	private String parentid;
	private Set tsysUsers = new HashSet(0);


	// Constructors

	/** default constructor */
	public TsysAreaCode()
	{
	}


	// Property accessors

	public String getAreacode()
	{
		return this.areacode;
	}

	public void setAreacode(String areacode)
	{
		this.areacode = areacode;
	}

	public String getAreaname()
	{
		return this.areaname;
	}

	public void setAreaname(String areaname)
	{
		this.areaname = areaname;
	}

	public String getAreadesc()
	{
		return this.areadesc;
	}

	public void setAreadesc(String areadesc)
	{
		this.areadesc = areadesc;
	}

	public String getParentid()
	{
		return this.parentid;
	}

	public void setParentid(String parentid)
	{
		this.parentid = parentid;
	}


	public Set getTsysUsers()
	{
		return this.tsysUsers;
	}

	public void setTsysUsers(Set tsysUsers)
	{
		this.tsysUsers = tsysUsers;
	}

	public Tree toTree() {
		Tree tree = new Tree(areacode,areaname);
		return tree;
	}

}