package com.uu800.admin.base.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TsysRole generated by MyEclipse Persistence Tools
 */

public class TsysRole implements java.io.Serializable
{

	// Fields

	private long roleid;
	private String rolename;
	private long roletype;
	private String comments;
	private long createuser;
	private Date createtime;
	private long modifyuser;
	private Date modifytime;
	private long rightobj;
	private long operatetype;
	private Set tsysUsers = new HashSet(0);
	private Set tsysRights = new HashSet(0);
	
	private String moduletype;
	private String roletypename;
	private String rightobjname;
	
	private boolean checked;

	// Constructors

	/** default constructor */
	public TsysRole()
	{
	}

	/** minimal constructor */
	public TsysRole(String rolename, long roletype, long createuser,
			Date createtime)
	{
		this.rolename = rolename;
		this.roletype = roletype;
		this.createuser = createuser;
		this.createtime = createtime;
	}

	/** full constructor */
	public TsysRole(String rolename, long roletype, String comments,
			long createuser, Date createtime, long modifyuser, Date modifytime,
			long rightobj, long operatetype, Set tsysUsers, Set tsysRights)
	{
		this.rolename = rolename;
		this.roletype = roletype;
		this.comments = comments;
		this.createuser = createuser;
		this.createtime = createtime;
		this.modifyuser = modifyuser;
		this.modifytime = modifytime;
		this.rightobj = rightobj;
		this.operatetype = operatetype;
		this.tsysUsers = tsysUsers;
		this.tsysRights = tsysRights;
	}

	// Property accessors

	public long getRoleid()
	{
		return this.roleid;
	}

	public void setRoleid(long roleid)
	{
		this.roleid = roleid;
	}

	public String getRolename()
	{
		return this.rolename;
	}

	public void setRolename(String rolename)
	{
		this.rolename = rolename;
	}

	public long getRoletype()
	{
		return this.roletype;
	}

	public void setRoletype(long roletype)
	{
		this.roletype = roletype;
	}

	public String getComments()
	{
		return this.comments;
	}

	public void setComments(String comments)
	{
		this.comments = comments;
	}

	public long getCreateuser()
	{
		return this.createuser;
	}

	public void setCreateuser(long createuser)
	{
		this.createuser = createuser;
	}

	public Date getCreatetime()
	{
		return this.createtime;
	}

	public void setCreatetime(Date createtime)
	{
		this.createtime = createtime;
	}

	public long getModifyuser()
	{
		return this.modifyuser;
	}

	public void setModifyuser(long modifyuser)
	{
		this.modifyuser = modifyuser;
	}

	public Date getModifytime()
	{
		return this.modifytime;
	}

	public void setModifytime(Date modifytime)
	{
		this.modifytime = modifytime;
	}

	public long getRightobj()
	{
		return this.rightobj;
	}

	public void setRightobj(long rightobj)
	{
		this.rightobj = rightobj;
	}

	public long getOperatetype()
	{
		return this.operatetype;
	}

	public void setOperatetype(long operatetype)
	{
		this.operatetype = operatetype;
	}

	public Set getTsysUsers()
	{
		return this.tsysUsers;
	}

	public void setTsysUsers(Set tsysUsers)
	{
		this.tsysUsers = tsysUsers;
	}

	public Set getTsysRights()
	{
		return this.tsysRights;
	}

	public void setTsysRights(Set tsysRights)
	{
		this.tsysRights = tsysRights;
	}

	public String getModuletype()
	{//0-SYS，1-ENT，2-USR  
		if(this.roletype == 1)
		{
			moduletype = "ENT";
		}
		else if(this.roletype == 2)
		{
			moduletype = "USR";
		}
		else
		{
			moduletype = "SYS";
		}
		return moduletype;
	}

	public String getRoletypename()
	{
		if(this.roletype == 1)
		{
			roletypename = "企业版";
		}
		else if(this.roletype == 2)
		{
			roletypename = "个人版";
		}
		else
		{
			roletypename = "运营商";
		}
		return roletypename;
	}

	public String getRightobjname()
	{
		if(this.rightobj==0)
		{
			rightobjname = "管理员";
		}
		else if(this.rightobj==1)
		{
			rightobjname = "子帐号";
		}
		else
		{
			rightobjname = "未知";	
		}
		
		return rightobjname;
	}
	
	
	public boolean isChecked() {
		return checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}
	
	

}