package com.uu800.admin.base.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TsysOrg generated by MyEclipse Persistence Tools
 */

public class TsysOrg implements java.io.Serializable
{

	// Fields

	private long orgid;
	private TsysOrg parentOrg;
	private String pathcode;
	private String orgtype;
	private String corpcode;
	private long grade;
	private String orgcode;
	private String orgshortname;
	private String orgenname;
	private String orgname;
	private String contactperson;
	private String contactphone;
	private String mobile;
	private String faxnum;
	private String comments;
	private long createuser;
	private Date createtime;
	private long modifyuser;
	private Date modifytime;
	private long areaid;
	private Set tsysUsers = new HashSet(0);
	private Set tsysOrgs = new HashSet(0);

	// Constructors

	/** default constructor */
	public TsysOrg()
	{
	}

	/** minimal constructor */
	public TsysOrg(String pathcode, String orgtype, long grade, String orgcode,
			String orgname, long createuser, Date createtime)
	{
		this.pathcode = pathcode;
		this.orgtype = orgtype;
		this.grade = grade;
		this.orgcode = orgcode;
		this.orgname = orgname;
		this.createuser = createuser;
		this.createtime = createtime;
	}

	/** full constructor */
	public TsysOrg(TsysOrg parentOrg, String pathcode, String orgtype,
			String corpcode, long grade, String orgcode, String orgshortname,
			String orgenname, String orgname,
			String contactperson, String contactphone, String mobile,
			String faxnum, String comments, long createuser, Date createtime,
			long modifyuser, Date modifytime, long areaid, Set tsysUsers,
			Set tsysOrgs)
	{
		this.parentOrg = parentOrg;
		this.pathcode = pathcode;
		this.orgtype = orgtype;
		this.corpcode = corpcode;
		this.grade = grade;
		this.orgcode = orgcode;
		this.orgshortname = orgshortname;
		this.orgenname = orgenname;
		this.orgname = orgname;
		this.contactperson = contactperson;
		this.contactphone = contactphone;
		this.mobile = mobile;
		this.faxnum = faxnum;
		this.comments = comments;
		this.createuser = createuser;
		this.createtime = createtime;
		this.modifyuser = modifyuser;
		this.modifytime = modifytime;
		this.areaid = areaid;
		this.tsysUsers = tsysUsers;
		this.tsysOrgs = tsysOrgs;
	}

	// Property accessors

	public long getOrgid()
	{
		return this.orgid;
	}

	public void setOrgid(long orgid)
	{
		this.orgid = orgid;
	}

	public TsysOrg getParentOrg()
	{
		return this.parentOrg;
	}

	public void setParentOrg(TsysOrg parentOrg)
	{
		this.parentOrg = parentOrg;
	}

	public String getPathcode()
	{
		return this.pathcode;
	}

	public void setPathcode(String pathcode)
	{
		this.pathcode = pathcode;
	}

	public String getOrgtype()
	{
		return this.orgtype;
	}

	public void setOrgtype(String orgtype)
	{
		this.orgtype = orgtype;
	}

	public String getCorpcode()
	{
		return this.corpcode;
	}

	public void setCorpcode(String corpcode)
	{
		this.corpcode = corpcode;
	}

	public long getGrade()
	{
		return this.grade;
	}

	public void setGrade(long grade)
	{
		this.grade = grade;
	}

	public String getOrgcode()
	{
		return this.orgcode;
	}

	public void setOrgcode(String orgcode)
	{
		this.orgcode = orgcode;
	}

	public String getOrgshortname()
	{
		return this.orgshortname;
	}

	public void setOrgshortname(String orgshortname)
	{
		this.orgshortname = orgshortname;
	}

	public String getOrgenname()
	{
		return this.orgenname;
	}

	public void setOrgenname(String orgenname)
	{
		this.orgenname = orgenname;
	}

	public String getOrgname()
	{
		return this.orgname;
	}

	public void setOrgname(String orgname)
	{
		this.orgname = orgname;
	}

	public String getContactperson()
	{
		return this.contactperson;
	}

	public void setContactperson(String contactperson)
	{
		this.contactperson = contactperson;
	}

	public String getContactphone()
	{
		return this.contactphone;
	}

	public void setContactphone(String contactphone)
	{
		this.contactphone = contactphone;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getFaxnum()
	{
		return this.faxnum;
	}

	public void setFaxnum(String faxnum)
	{
		this.faxnum = faxnum;
	}

	public String getComments()
	{
		return this.comments;
	}

	public void setComments(String comments)
	{
		this.comments = comments;
	}

	public long getCreateuser()
	{
		return this.createuser;
	}

	public void setCreateuser(long createuser)
	{
		this.createuser = createuser;
	}

	public Date getCreatetime()
	{
		return this.createtime;
	}

	public void setCreatetime(Date createtime)
	{
		this.createtime = createtime;
	}

	public long getModifyuser()
	{
		return this.modifyuser;
	}

	public void setModifyuser(long modifyuser)
	{
		this.modifyuser = modifyuser;
	}

	public Date getModifytime()
	{
		return this.modifytime;
	}

	public void setModifytime(Date modifytime)
	{
		this.modifytime = modifytime;
	}

	public long getAreaid()
	{
		return this.areaid;
	}

	public void setAreaid(long areaid)
	{
		this.areaid = areaid;
	}

	public Set getTsysUsers()
	{
		return this.tsysUsers;
	}

	public void setTsysUsers(Set tsysUsers)
	{
		this.tsysUsers = tsysUsers;
	}

	public Set getTsysOrgs()
	{
		return this.tsysOrgs;
	}

	public void setTsysOrgs(Set tsysOrgs)
	{
		this.tsysOrgs = tsysOrgs;
	}

}