package com.uu800.admin.base.entity;

import java.util.Date;

/**
 * TsysLogs generated by MyEclipse Persistence Tools
 */

public class TsysLogs implements java.io.Serializable
{

	// Fields

	private long logid;
	private long userid;
	private long enterpriseid;
	private String usertype;
	private Date logtime;
	private int logtype;
	private String logmessage;
	private String ipaddr;
	private String areacode;
	private String username;
	private String corpname;
	private boolean result;

	// Constructors

	/** default constructor */
	public TsysLogs()
	{
	}
	
	/** default constructor */
	public TsysLogs(String logmessage,int logtype,boolean result) {
		this.logmessage=logmessage;
		this.logtype=logtype;
		//this.result=result;
	}


	/** full constructor */
	public TsysLogs(long userid, long enterpriseid, String usertype, Date logtime,
			int logtype, String logmessage, String ipaddr, String areacode,
			String username, String corpname, boolean result)
	{
		this.userid = userid;
		this.enterpriseid = enterpriseid;
		this.usertype = usertype;
		this.logtime = logtime;
		this.logtype = logtype;
		this.logmessage = logmessage;
		this.ipaddr = ipaddr;
		this.areacode = areacode;
		this.username = username;
		this.corpname = corpname;
		this.result = result;
	}

	// Property accessors

	public long getLogid()
	{
		return this.logid;
	}

	public void setLogid(long logid)
	{
		this.logid = logid;
	}

	public long getUserid()
	{
		return this.userid;
	}

	public void setUserid(long userid)
	{
		this.userid = userid;
	}

	public long getEnterpriseid()
	{
		return this.enterpriseid;
	}

	public void setEnterpriseid(long enterpriseid)
	{
		this.enterpriseid = enterpriseid;
	}

	public String getUsertype()
	{
		return this.usertype;
	}

	public void setUsertype(String usertype)
	{
		this.usertype = usertype;
	}

	public Date getLogtime()
	{
		return this.logtime;
	}

	public void setLogtime(Date logtime)
	{
		this.logtime = logtime;
	}

	public int getLogtype()
	{
		return this.logtype;
	}

	public void setLogtype(int logtype)
	{
		this.logtype = logtype;
	}

	public String getLogmessage()
	{
		return this.logmessage;
	}

	public void setLogmessage(String logmessage)
	{
		this.logmessage = logmessage;
	}

	public String getIpaddr()
	{
		return this.ipaddr;
	}

	public void setIpaddr(String ipaddr)
	{
		this.ipaddr = ipaddr;
	}

	public String getAreacode()
	{
		return this.areacode;
	}

	public void setAreacode(String areacode)
	{
		this.areacode = areacode;
	}

	public String getUsername()
	{
		return this.username;
	}

	public void setUsername(String username)
	{
		this.username = username;
	}

	public String getCorpname()
	{
		return this.corpname;
	}

	public void setCorpname(String corpname)
	{
		this.corpname = corpname;
	}

	public boolean getResult()
	{
		return this.result;
	}

	public void setResult(boolean result)
	{
		this.result = result;
	}

}