package com.sxit.workflow.model;
// Generated 2007-11-7 15:43:22 by Hibernate Tools 3.2.0.b9



/**
 * TwflDirection generated by hbm2java
 */
public class TwflDirection  implements java.io.Serializable {


     private int directionid;
     private String directionname;
     private String description;
     private TwflNode fromNode;
     private TwflNode toNode;

    public TwflDirection() {
    }

    public TwflDirection(String directionname, String description, TwflNode fromNode, TwflNode toNode) {
       this.directionname = directionname;
       this.description = description;
       this.fromNode = fromNode;
       this.toNode = toNode;
    }
   
    public int getDirectionid() {
        return this.directionid;
    }
    
    public void setDirectionid(int directionid) {
        this.directionid = directionid;
    }
    public String getDirectionname() {
        return this.directionname;
    }
    
    public void setDirectionname(String directionname) {
        this.directionname = directionname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public TwflNode getFromNode() {
        return this.fromNode;
    }
    
    public void setFromNode(TwflNode fromNode) {
        this.fromNode = fromNode;
    }
    public TwflNode getToNode() {
        return this.toNode;
    }
    
    public void setToNode(TwflNode toNode) {
        this.toNode = toNode;
    }




}


