package com.sxit.workflow.model;
// Generated 2007-12-27 15:10:43 by Hibernate Tools 3.2.0.b9


import com.sxit.system.model.TsysModule;
import com.sxit.system.model.TsysUser;
import java.util.HashSet;
import java.util.Set;

/**
 * TwflBusiness generated by hbm2java
 */
public class TwflBusiness  implements java.io.Serializable {


     private int businessid;
     private String businessname;
     private int usetype;
     private int statusid;
     private int ordernum;
     private TsysModule module;
     private Set<TsysUser> users = new HashSet<TsysUser>(0);

    public TwflBusiness() {
    }

    public TwflBusiness(String businessname, int usetype, int statusid, int ordernum, TsysModule module, Set<TsysUser> users) {
       this.businessname = businessname;
       this.usetype = usetype;
       this.statusid = statusid;
       this.ordernum = ordernum;
       this.module = module;
       this.users = users;
    }
   
    public int getBusinessid() {
        return this.businessid;
    }
    
    public void setBusinessid(int businessid) {
        this.businessid = businessid;
    }
    public String getBusinessname() {
        return this.businessname;
    }
    
    public void setBusinessname(String businessname) {
        this.businessname = businessname;
    }
    public int getUsetype() {
        return this.usetype;
    }
    
    public void setUsetype(int usetype) {
        this.usetype = usetype;
    }
    public int getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(int statusid) {
        this.statusid = statusid;
    }
    public int getOrdernum() {
        return this.ordernum;
    }
    
    public void setOrdernum(int ordernum) {
        this.ordernum = ordernum;
    }
    public TsysModule getModule() {
        return this.module;
    }
    
    public void setModule(TsysModule module) {
        this.module = module;
    }
    public Set<TsysUser> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<TsysUser> users) {
        this.users = users;
    }




}


