package com.sxit.workflow.model;
// Generated 2007-11-20 17:31:31 by Hibernate Tools 3.2.0.b9



/**
 * TwflBusinessUser generated by hbm2java
 */
public class TwflBusinessUser  implements java.io.Serializable {


     private TwflBusinessUserPK comp_id;

    public TwflBusinessUser() {
    }

    public TwflBusinessUser(TwflBusinessUserPK comp_id) {
       this.comp_id = comp_id;
    }
   
    public TwflBusinessUserPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(TwflBusinessUserPK comp_id) {
        this.comp_id = comp_id;
    }




}


