package com.sxit.workflow.model;
// Generated 2007-12-20 14:26:39 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import com.sxit.system.model.TsysRole;

/**
 * TwflNode generated by hbm2java
 */
public class TwflNode  implements java.io.Serializable {


     private int nodeid;
     private String nodename;
     private String description;
     private String image;
     private byte nodetype;
     private int xcoordinate;
     private int ycoordinate;
     private int width;
     private int height;
     private byte nodedotype;
     private byte bodydotype;
     private byte flowdotype;
     private byte attachdotype;
     private boolean sendemail;
     private boolean sendsms;
     private boolean jumpself;
     private TwflProcess twflProcess;
//     private TsysPosition tsysPosition;
     private TsysRole tsysRole;
     private Set<TwflDirection> fromNode = new HashSet<TwflDirection>(0);
     private Set<TwflDirection> toNode = new HashSet<TwflDirection>(0);
     private Set<TwflAction> actions = new HashSet<TwflAction>(0);

    public TwflNode() {
    }


    public TwflNode(int nodeid) {
        this.nodeid = nodeid;
    }
//    public TwflNode(int nodeid, String nodename, String description, String image, byte nodetype, int xcoordinate, int ycoordinate, int width, int height, byte nodedotype, byte bodydotype, byte flowdotype, byte attachdotype, boolean sendemail, boolean sendsms, boolean jumpself, TwflProcess twflProcess, TsysPosition tsysPosition, Set<TwflDirection> fromNode, Set<TwflDirection> toNode) {
//       this.nodeid = nodeid;
//       this.nodename = nodename;
//       this.description = description;
//       this.image = image;
//       this.nodetype = nodetype;
//       this.xcoordinate = xcoordinate;
//       this.ycoordinate = ycoordinate;
//       this.width = width;
//       this.height = height;
//       this.nodedotype = nodedotype;
//       this.bodydotype = bodydotype;
//       this.flowdotype = flowdotype;
//       this.attachdotype = attachdotype;
//       this.sendemail = sendemail;
//       this.sendsms = sendsms;
//       this.jumpself = jumpself;
//       this.twflProcess = twflProcess;
//       this.tsysPosition = tsysPosition;
//       this.fromNode = fromNode;
//       this.toNode = toNode;
//    }

    public int getNodeid() {
        return this.nodeid;
    }

    public void setNodeid(int nodeid) {
        this.nodeid = nodeid;
    }
    public String getNodename() {
        return this.nodename;
    }

    public void setNodename(String nodename) {
        this.nodename = nodename;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }
    public byte getNodetype() {
        return this.nodetype;
    }

    public void setNodetype(byte nodetype) {
        this.nodetype = nodetype;
    }
    public int getXcoordinate() {
        return this.xcoordinate;
    }

    public void setXcoordinate(int xcoordinate) {
        this.xcoordinate = xcoordinate;
    }
    public int getYcoordinate() {
        return this.ycoordinate;
    }

    public void setYcoordinate(int ycoordinate) {
        this.ycoordinate = ycoordinate;
    }
    public int getWidth() {
        return this.width;
    }

    public void setWidth(int width) {
        this.width = width;
    }
    public int getHeight() {
        return this.height;
    }

    public void setHeight(int height) {
        this.height = height;
    }
    public byte getNodedotype() {
        return this.nodedotype;
    }

    public void setNodedotype(byte nodedotype) {
        this.nodedotype = nodedotype;
    }
    public byte getBodydotype() {
        return this.bodydotype;
    }

    public void setBodydotype(byte bodydotype) {
        this.bodydotype = bodydotype;
    }
    public byte getFlowdotype() {
        return this.flowdotype;
    }

    public void setFlowdotype(byte flowdotype) {
        this.flowdotype = flowdotype;
    }
    public byte getAttachdotype() {
        return this.attachdotype;
    }

    public void setAttachdotype(byte attachdotype) {
        this.attachdotype = attachdotype;
    }
    public boolean isSendemail() {
        return this.sendemail;
    }

    public void setSendemail(boolean sendemail) {
        this.sendemail = sendemail;
    }
    public boolean isSendsms() {
        return this.sendsms;
    }

    public void setSendsms(boolean sendsms) {
        this.sendsms = sendsms;
    }
    public boolean isJumpself() {
        return this.jumpself;
    }

    public void setJumpself(boolean jumpself) {
        this.jumpself = jumpself;
    }
    public TwflProcess getTwflProcess() {
        return this.twflProcess;
    }

    public void setTwflProcess(TwflProcess twflProcess) {
        this.twflProcess = twflProcess;
    }
//    public TsysPosition getTsysPosition() {
//        return this.tsysPosition;
//    }
//
//    public void setTsysPosition(TsysPosition tsysPosition) {
//        this.tsysPosition = tsysPosition;
//    }
    public Set<TwflDirection> getFromNode() {
        return this.fromNode;
    }

    public void setFromNode(Set<TwflDirection> fromNode) {
        this.fromNode = fromNode;
    }
    public Set<TwflDirection> getToNode() {
        return this.toNode;
    }

    public void setToNode(Set<TwflDirection> toNode) {
        this.toNode = toNode;
    }

    public boolean equals(Object other) {
        if ( !(other instanceof TwflNode) ) return false;
        TwflNode castOther = (TwflNode) other;
        return new EqualsBuilder()
            .append(this.getNodeid(), castOther.getNodeid())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getNodeid())
            .toHashCode();
    }


	/**
	 * @return the actions
	 */
	public Set<TwflAction> getActions() {
		return actions;
	}


	/**
	 * @param actions the actions to set
	 */
	public void setActions(Set<TwflAction> actions) {
		this.actions = actions;
	}


	/**
	 * @return the tsysUserRole
	 */
	public TsysRole getTsysRole() {
		return tsysRole;
	}


	/**
	 * @param tsysRole the tsysRole to set
	 */
	public void setTsysRole(TsysRole tsysRole) {
		this.tsysRole = tsysRole;
	}






}


