package com.sxit.workflow.model;

import com.sxit.system.model.TsysUserRolePK;
import com.sxit.system.model.TsysDepartmentPositionPK;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
// Generated 2007-11-20 17:31:31 by Hibernate Tools 3.2.0.b9



/**
 * TwflBusinessUserPK generated by hbm2java
 */
public class TwflBusinessUserPK  implements java.io.Serializable {


     private long userid;
     private int businessid;

    public TwflBusinessUserPK() {
    }

    public TwflBusinessUserPK(long userid, int businessid) {
       this.userid = userid;
       this.businessid = businessid;
    }

    public long getUserid() {
        return this.userid;
    }

    public void setUserid(long userid) {
        this.userid = userid;
    }
    public int getBusinessid() {
        return this.businessid;
    }

    public void setBusinessid(int businessid) {
        this.businessid = businessid;
    }

    public boolean equals(Object other) {
        if ( !(other instanceof TwflBusinessUserPK) ) return false;
        TwflBusinessUserPK castOther = (TwflBusinessUserPK) other;
        return new EqualsBuilder()
            .append(this.getBusinessid(), castOther.getBusinessid())
            .append(this.getUserid(), castOther.getUserid())
            .isEquals();
    }
    public int hashCode() {
      return new HashCodeBuilder()
          .append(getBusinessid())
          .append(getUserid())
          .toHashCode();
    }
}


