
package com.changpeng.models;

// Generated 2008-5-5 10:58:11 by Hibernate Tools 3.2.0.CR1

/**
 * JifentongjiId generated by hbm2java
 */
public class JifentongjiId implements java.io.Serializable {

	private String username;
	private Integer userid;
	private String groupname;
	private Double xianchang;
	private Double video;
	private Double doc;
	private Double budeng;
	private Double koufen;
	private Double zongjifen;

	public JifentongjiId() {
	}

	public JifentongjiId(String groupname) {
		this.groupname = groupname;
	}

	public JifentongjiId(String username, String groupname, Double xianchang, Double video, Double doc, Double budeng, Double koufen, Double zongjifen) {
		this.username = username;
		this.groupname = groupname;
		this.xianchang = xianchang;
		this.video = video;
		this.doc = doc;
		this.budeng = budeng;
		this.koufen = koufen;
		this.zongjifen = zongjifen;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	public Double getXianchang() {
		return this.xianchang;
	}

	public void setXianchang(Double xianchang) {
		this.xianchang = xianchang;
	}

	public Double getVideo() {
		return this.video;
	}

	public void setVideo(Double video) {
		this.video = video;
	}

	public Double getDoc() {
		return this.doc;
	}

	public void setDoc(Double doc) {
		this.doc = doc;
	}

	public Double getBudeng() {
		return this.budeng;
	}

	public void setBudeng(Double budeng) {
		this.budeng = budeng;
	}

	public Double getKoufen() {
		return this.koufen;
	}

	public void setKoufen(Double koufen) {
		this.koufen = koufen;
	}

	public Double getZongjifen() {
		return this.zongjifen;
	}

	public void setZongjifen(Double zongjifen) {
		this.zongjifen = zongjifen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JifentongjiId))
			return false;
		JifentongjiId castOther = (JifentongjiId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null && castOther.getUsername() != null && this
				.getUsername().equals(castOther.getUsername())))
				&& ((this.getGroupname() == castOther.getGroupname()) || (this.getGroupname() != null && castOther.getGroupname() != null && this
						.getGroupname().equals(castOther.getGroupname())))
				&& ((this.getXianchang() == castOther.getXianchang()) || (this.getXianchang() != null && castOther.getXianchang() != null && this
						.getXianchang().equals(castOther.getXianchang())))
				&& ((this.getVideo() == castOther.getVideo()) || (this.getVideo() != null && castOther.getVideo() != null && this.getVideo().equals(
						castOther.getVideo())))
				&& ((this.getDoc() == castOther.getDoc()) || (this.getDoc() != null && castOther.getDoc() != null && this.getDoc().equals(
						castOther.getDoc())))
				&& ((this.getBudeng() == castOther.getBudeng()) || (this.getBudeng() != null && castOther.getBudeng() != null && this.getBudeng()
						.equals(castOther.getBudeng())))
				&& ((this.getKoufen() == castOther.getKoufen()) || (this.getKoufen() != null && castOther.getKoufen() != null && this.getKoufen()
						.equals(castOther.getKoufen())))
				&& ((this.getZongjifen() == castOther.getZongjifen()) || (this.getZongjifen() != null && castOther.getZongjifen() != null && this
						.getZongjifen().equals(castOther.getZongjifen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getGroupname() == null ? 0 : this.getGroupname().hashCode());
		result = 37 * result + (getXianchang() == null ? 0 : this.getXianchang().hashCode());
		result = 37 * result + (getVideo() == null ? 0 : this.getVideo().hashCode());
		result = 37 * result + (getDoc() == null ? 0 : this.getDoc().hashCode());
		result = 37 * result + (getBudeng() == null ? 0 : this.getBudeng().hashCode());
		result = 37 * result + (getKoufen() == null ? 0 : this.getKoufen().hashCode());
		result = 37 * result + (getZongjifen() == null ? 0 : this.getZongjifen().hashCode());
		return result;
	}

	/**
	 * @return the userid
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * @param userid the userid to set
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

}
