
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;

import com.changpeng.models.system.SysUser;

/**
 * Jifenbudeng generated by hbm2java
 */
public class Jifenbudeng implements java.io.Serializable {

	private int budengid;
	private String title;
	private String budengdate;
	private SysUser lawer;
	private String lawerno;
	private Float xuefen;
	private String createuser;
	private Timestamp createtime;

	public Jifenbudeng() {
	}

	

	public int getBudengid() {
		return this.budengid;
	}

	public void setBudengid(int budengid) {
		this.budengid = budengid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBudengdate() {
		return this.budengdate;
	}

	public void setBudengdate(String budengdate) {
		this.budengdate = budengdate;
	}

	public SysUser getLawer() {
		return this.lawer;
	}

	public void setLawer(SysUser lawer) {
		this.lawer = lawer;
	}

	public String getLawerno() {
		return this.lawerno;
	}

	public void setLawerno(String lawerno) {
		this.lawerno = lawerno;
	}

	public Float getXuefen() {
		return this.xuefen;
	}

	public void setXuefen(Float xuefen) {
		this.xuefen = xuefen;
	}

	public String getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

}
