
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;

/**
 * Lxnetrecs generated by hbm2java
 */
public class Lxnetrecs implements java.io.Serializable {

	private int netrecsid;
	private int lessonid;
	private int userid;
	private float allminutes;
	private float lookedminutes;
	private Timestamp lasttime;

	
	private String remarks;
	/**
	 * @return the remarks
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * @param remarks the remarks to set
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Lxnetrecs() {
	}

	public Lxnetrecs(int lessonid, int userid, float allminutes, float lookedminutes, Timestamp lasttime) {
		this.lessonid = lessonid;
		this.userid = userid;
		this.allminutes = allminutes;
		this.lookedminutes = lookedminutes;
		this.lasttime = lasttime;
	}

	public int getNetrecsid() {
		return this.netrecsid;
	}

	public void setNetrecsid(int netrecsid) {
		this.netrecsid = netrecsid;
	}

	public int getLessonid() {
		return this.lessonid;
	}

	public void setLessonid(int lessonid) {
		this.lessonid = lessonid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public float getAllminutes() {
		return this.allminutes;
	}

	public void setAllminutes(float allminutes) {
		this.allminutes = allminutes;
	}

	public float getLookedminutes() {
		return this.lookedminutes;
	}

	public void setLookedminutes(float lookedminutes) {
		this.lookedminutes = lookedminutes;
	}

	public Timestamp getLasttime() {
		return this.lasttime;
	}

	public void setLasttime(Timestamp lasttime) {
		this.lasttime = lasttime;
	}

}
