package com.sxit.system.model;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9



/**
 * TsysFunctionRolePK generated by hbm2java
 */
public class TsysFunctionRolePK  implements java.io.Serializable {


     private TsysRole tsysRole;
     private TsysFunction tsysFunction;

    public TsysFunctionRolePK() {
    }

    public TsysFunctionRolePK(TsysRole tsysRole, TsysFunction tsysFunction) {
       this.tsysRole = tsysRole;
       this.tsysFunction = tsysFunction;
    }

    public TsysRole getTsysRole() {
        return this.tsysRole;
    }

    public void setTsysRole(TsysRole tsysRole) {
        this.tsysRole = tsysRole;
    }
    public TsysFunction getTsysFunction() {
        return this.tsysFunction;
    }

    public void setTsysFunction(TsysFunction tsysFunction) {
        this.tsysFunction = tsysFunction;
    }
    public boolean equals(Object other) {
        if ( !(other instanceof TsysFunctionRolePK) ) return false;
        TsysFunctionRolePK castOther = (TsysFunctionRolePK) other;
        return new EqualsBuilder()
            .append(this.getTsysFunction().getFunctionid(), castOther.getTsysFunction().getFunctionid())
            .append(this.getTsysRole().getRoleid(),  castOther.getTsysRole().getRoleid())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getTsysRole().getRoleid())
            .append(getTsysFunction().getFunctionid())
            .toHashCode();
    }



}


