package com.sxit.system.model;

import org.apache.commons.lang.builder.HashCodeBuilder;

import org.apache.commons.lang.builder.EqualsBuilder;
// Generated 2007-10-12 14:12:09 by Hibernate Tools 3.2.0.b9

/**
 * TsysDepartmentPositionPK generated by hbm2java
 */
public class TsysDepartmentPositionPK  implements java.io.Serializable {


     private TsysDepartment tsysDepartment;
     private TsysPosition tsysPosition;

    public TsysDepartmentPositionPK() {
    }

    public TsysDepartmentPositionPK(TsysDepartment tsysDepartment, TsysPosition tsysPosition) {
       this.tsysDepartment = tsysDepartment;
       this.tsysPosition = tsysPosition;
    }

    public TsysDepartment getTsysDepartment() {
        return this.tsysDepartment;
    }

    public void setTsysDepartment(TsysDepartment tsysDepartment) {
        this.tsysDepartment = tsysDepartment;
    }
    public TsysPosition getTsysPosition() {
        return this.tsysPosition;
    }

    public void setTsysPosition(TsysPosition tsysPosition) {
        this.tsysPosition = tsysPosition;
    }

    public boolean equals(Object other) {
        if ( !(other instanceof TsysDepartmentPositionPK) ) return false;
        TsysDepartmentPositionPK castOther = (TsysDepartmentPositionPK) other;
        return new EqualsBuilder()
            .append(this.getTsysDepartment().getDepartmentid(), castOther.getTsysDepartment().getDepartmentid())
            .append(this.getTsysPosition().getPositionid(),  castOther.getTsysPosition().getPositionid())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getTsysDepartment().getDepartmentid())
            .append(getTsysPosition().getPositionid())
            .toHashCode();
    }
}


