package com.sxit.system.model;
// Generated 2007-11-5 15:08:22 by Hibernate Tools 3.2.0.b9


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TsysDepartment generated by hbm2java
 */
public class TsysDepartment  implements java.io.Serializable {
 

     private int departmentid;
     private String departmentname;
     private String description;
     private String displayname;
     private int type;
     private int statusid;
     private String phone;
     private String linkman;
     private String address;
     private Timestamp createtime;
     private Set<TsysUser> tsysUsers = new HashSet<TsysUser>(0);
     private Set<TsysDepartment> children = new HashSet<TsysDepartment>(0);
     private TsysDepartment parent;
     private Set<TsysDepartmentPosition> tsysDepartmentPositions = new HashSet<TsysDepartmentPosition>(0);

    public TsysDepartment() {
    }

  
    public int getDepartmentid() {
        return this.departmentid;
    }
    
    public void setDepartmentid(int departmentid) {
        this.departmentid = departmentid;
    }
    public String getDepartmentname() {
        return this.departmentname;
    }
    
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public int getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(int statusid) {
        this.statusid = statusid;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getLinkman() {
        return this.linkman;
    }
    
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }
    public String getAddress() {
        return this.address;
    } 
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Timestamp getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }
    public Set<TsysUser> getTsysUsers() {
        return this.tsysUsers;
    }
    
    public void setTsysUsers(Set<TsysUser> tsysUsers) {
        this.tsysUsers = tsysUsers;
    }
    public Set<TsysDepartment> getChildren() {
        return this.children;
    }
    
    public void setChildren(Set<TsysDepartment> children) {
        this.children = children;
    }
    public TsysDepartment getParent() {
        return this.parent;
    }
    
    public void setParent(TsysDepartment parent) {
        this.parent = parent;
    }
    public Set<TsysDepartmentPosition> getTsysDepartmentPositions() {
        return this.tsysDepartmentPositions;
    }
    
    public void setTsysDepartmentPositions(Set<TsysDepartmentPosition> tsysDepartmentPositions) {
        this.tsysDepartmentPositions = tsysDepartmentPositions;
    }




}


