package com.sxit.system.model;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9



/**
 * TsysUserRolePK generated by hbm2java
 */
public class TsysUserRolePK  implements java.io.Serializable {


  private TsysUser tsysUser;
  private TsysRole tsysRole;

  public TsysUserRolePK() {
  }

  public TsysUserRolePK(TsysUser tsysUser, TsysRole tsysRole) {
    this.tsysUser = tsysUser;
    this.tsysRole = tsysRole;
  }

  public TsysUser getTsysUser() {
    return this.tsysUser;
  }

  public void setTsysUser(TsysUser tsysUser) {
    this.tsysUser = tsysUser;
  }

  public TsysRole getTsysRole() {
    return this.tsysRole;
  }

  public void setTsysRole(TsysRole tsysRole) {
    this.tsysRole = tsysRole;
  }
  public boolean equals(Object other) {
    if (! (other instanceof TsysUserRolePK))
      return false;
    TsysUserRolePK castOther = (TsysUserRolePK) other;
    return new EqualsBuilder()
        .append(this.getTsysRole(),
                castOther.getTsysRole())
        .append(this.getTsysUser(),
                castOther.getTsysUser())
        .isEquals();
  }

  public int hashCode() {
    return new HashCodeBuilder()
        .append(getTsysRole())
        .append(getTsysUser())
        .toHashCode();
  }
}



