package com.sxit.system.model;
// Generated 2007-10-12 12:06:26 by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;

/**
 * TsysPosition generated by hbm2java
 */
public class TsysPosition  implements java.io.Serializable {

	
     private int positionid;
     private String positionname;
     private String mark;
     private int type;
     private Set<TsysDepartmentPosition> tsysDepartmentPositions = new HashSet<TsysDepartmentPosition>(0);

    public TsysPosition() {
    }

    public TsysPosition(String positionname, int type, Set<TsysDepartmentPosition> tsysDepartmentPositions) {
       this.positionname = positionname;
       this.type = type;
       this.tsysDepartmentPositions = tsysDepartmentPositions;
    }
   
    public int getPositionid() {
        return this.positionid;
    }
    
    public void setPositionid(int positionid) {
        this.positionid = positionid;
    }
    public String getPositionname() {
        return this.positionname;
    }
    
    public void setPositionname(String positionname) {
        this.positionname = positionname;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public Set<TsysDepartmentPosition> getTsysDepartmentPositions() {
        return this.tsysDepartmentPositions;
    }
    
    public void setTsysDepartmentPositions(Set<TsysDepartmentPosition> tsysDepartmentPositions) {
        this.tsysDepartmentPositions = tsysDepartmentPositions;
    }

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}




}


