package com.sxit.system.model;
// Generated 2007-10-10 15:50:37 by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;

/**
 * TsysFunction generated by hbm2java
 */
public class TsysFunction  implements java.io.Serializable {


     private String functionid;
     private String functionname;
     private String description;
     private String url;
     private String iconname;
     private boolean iscommon;
     private boolean ismenu;
     private short functionorder;
     private Set<TsysFunctionUser> tsysFunctionUsers = new HashSet<TsysFunctionUser>(0);
     private Set<TsysFunctionRole> tsysFunctionRoles = new HashSet<TsysFunctionRole>(0);
     private TsysModule tsysModule;

    public TsysFunction() {
    }


    public TsysFunction(String functionid) {
        this.functionid = functionid;
    }
    public TsysFunction(String functionid, String functionname, String description, String url, String iconname, boolean iscommon,short functionorder, Set<TsysFunctionUser> tsysFunctionUsers, Set<TsysFunctionRole> tsysFunctionRoles, TsysModule tsysModule) {
       this.functionid = functionid;
       this.functionname = functionname;
       this.description = description;
       this.url = url;
       this.iconname = iconname;
       this.iscommon = iscommon;
       this.functionorder= functionorder;
       this.tsysFunctionUsers = tsysFunctionUsers;
       this.tsysFunctionRoles = tsysFunctionRoles;
       this.tsysModule = tsysModule;
    }

    public String getFunctionid() {
        return this.functionid;
    }

    public void setFunctionid(String functionid) {
        this.functionid = functionid;
    }
    public String getFunctionname() {
        return this.functionname;
    }

    public void setFunctionname(String functionname) {
        this.functionname = functionname;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
    public String getIconname() {
        return this.iconname;
    }

    public void setIconname(String iconname) {
        this.iconname = iconname;
    }
    public short getFunctionorder() {
        return this.functionorder;
    }

    public void setFunctionorder(short functionorder) {
        this.functionorder = functionorder;
    }

    public boolean isIscommon() {
        return this.iscommon;
    }

    public void setIscommon(boolean iscommon) {
        this.iscommon = iscommon;
    }
    public Set<TsysFunctionUser> getTsysFunctionUsers() {
        return this.tsysFunctionUsers;
    }

    public void setTsysFunctionUsers(Set<TsysFunctionUser> tsysFunctionUsers) {
        this.tsysFunctionUsers = tsysFunctionUsers;
    }
    public Set<TsysFunctionRole> getTsysFunctionRoles() {
        return this.tsysFunctionRoles;
    }

    public void setTsysFunctionRoles(Set<TsysFunctionRole> tsysFunctionRoles) {
        this.tsysFunctionRoles = tsysFunctionRoles;
    }
    public TsysModule getTsysModule() {
        return this.tsysModule;
    }

    public void setTsysModule(TsysModule tsysModule) {
        this.tsysModule = tsysModule;
    }


	public boolean isIsmenu() {
		return ismenu;
	}


	public void setIsmenu(boolean ismenu) {
		this.ismenu = ismenu;
	}




}


