package com.sxit.system.model;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TsysGroup generated by hbm2java
 */
public class TsysGroup  implements java.io.Serializable {


     private int groupid;
     private String groupname;
     private String description;
     private Timestamp createtime;
     private int statusid;
     private Set<TsysGroupUser> tsysGroupUsers = new HashSet<TsysGroupUser>(0);

    public TsysGroup() {
    }

    public TsysGroup(String groupname, String description, Timestamp createtime, int statusid, Set<TsysGroupUser> tsysGroupUsers) {
       this.groupname = groupname;
       this.description = description;
       this.createtime = createtime;
       this.statusid = statusid;
       this.tsysGroupUsers = tsysGroupUsers;
    }
   
    public int getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Timestamp getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }
    public int getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(int statusid) {
        this.statusid = statusid;
    }
    public Set<TsysGroupUser> getTsysGroupUsers() {
        return this.tsysGroupUsers;
    }
    
    public void setTsysGroupUsers(Set<TsysGroupUser> tsysGroupUsers) {
        this.tsysGroupUsers = tsysGroupUsers;
    }




}


