package com.sxit.system.model;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9



/**
 * TsysGroupUser generated by hbm2java
 */
public class TsysGroupUser  implements java.io.Serializable {


     private TsysGroupUserPK comp_id;

    public TsysGroupUser() {
    }

    public TsysGroupUser(TsysGroupUserPK comp_id) {
       this.comp_id = comp_id;
    }
   
    public TsysGroupUserPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(TsysGroupUserPK comp_id) {
        this.comp_id = comp_id;
    }




}


