package com.sxit.system.model;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9



/**
 * TsysGroupUserPK generated by hbm2java
 */
public class TsysGroupUserPK  implements java.io.Serializable {


     private TsysUser tsysUser;
     private TsysGroup tsysGroup;

    public TsysGroupUserPK() {
    }

    public TsysGroupUserPK(TsysUser tsysUser, TsysGroup tsysGroup) {
       this.tsysUser = tsysUser;
       this.tsysGroup = tsysGroup;
    }

    public TsysUser getTsysUser() {
        return this.tsysUser;
    }

    public void setTsysUser(TsysUser tsysUser) {
        this.tsysUser = tsysUser;
    }
    public TsysGroup getTsysGroup() {
        return this.tsysGroup;
    }

    public void setTsysGroup(TsysGroup tsysGroup) {
        this.tsysGroup = tsysGroup;
    }
    public boolean equals(Object other) {
        if ( !(other instanceof TsysGroupUserPK) ) return false;
        TsysGroupUserPK castOther = (TsysGroupUserPK) other;
        return new EqualsBuilder()
            .append(this.getTsysGroup().getGroupid(), castOther.getTsysGroup().getGroupid())
            .append(this.getTsysUser().getUserid(),  castOther.getTsysUser().getUserid())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getTsysGroup().getGroupid())
            .append(getTsysUser().getUserid())
            .toHashCode();
    }



}


