package com.sxit.system.model;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9



/**
 * TsysUserRole generated by hbm2java
 */
public class TsysUserRole  implements java.io.Serializable {


     private TsysUserRolePK comp_id;

    public TsysUserRole() {
    }

    public TsysUserRole(TsysUserRolePK comp_id) {
       this.comp_id = comp_id;
    }
   
    public TsysUserRolePK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(TsysUserRolePK comp_id) {
        this.comp_id = comp_id;
    }




}


