package com.sxit.system.model;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;

/**
 * TsysModule generated by hbm2java
 */
public class TsysModule  implements java.io.Serializable {


     private String moduleid;
     private String modulename;
     private String description;
     private short moduleorder;
     private int powertype;
     private Set<TsysFunction> tsysFunctions = new HashSet<TsysFunction>(0);
     private Set<TsysPower> tsysPowers = new HashSet<TsysPower>(0);

    public TsysModule() {
    }

	
    public TsysModule(String moduleid) {
        this.moduleid = moduleid;
    }
    public TsysModule(String moduleid, String modulename, String description, short moduleorder, int powertype, Set<TsysFunction> tsysFunctions, Set<TsysPower> tsysPowers) {
       this.moduleid = moduleid;
       this.modulename = modulename;
       this.description = description;
       this.moduleorder = moduleorder;
       this.powertype = powertype;
       this.tsysFunctions = tsysFunctions;
       this.tsysPowers = tsysPowers;
    }
   
    public String getModuleid() {
        return this.moduleid;
    }
    
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid;
    }
    public String getModulename() {
        return this.modulename;
    }
    
    public void setModulename(String modulename) {
        this.modulename = modulename;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public short getModuleorder() {
        return this.moduleorder;
    }
    
    public void setModuleorder(short moduleorder) {
        this.moduleorder = moduleorder;
    }
    public int getPowertype() {
        return this.powertype;
    }
    
    public void setPowertype(int powertype) {
        this.powertype = powertype;
    }
    public Set<TsysFunction> getTsysFunctions() {
        return this.tsysFunctions;
    }
    
    public void setTsysFunctions(Set<TsysFunction> tsysFunctions) {
        this.tsysFunctions = tsysFunctions;
    }
    public Set<TsysPower> getTsysPowers() {
        return this.tsysPowers;
    }
    
    public void setTsysPowers(Set<TsysPower> tsysPowers) {
        this.tsysPowers = tsysPowers;
    }




}


