package com.sxit.system.model;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9



/**
 * TsysFunctionUserPK generated by hbm2java
 */
public class TsysFunctionUserPK  implements java.io.Serializable {


     private TsysUser tsysUser;
     private TsysFunction tsysFunction;

    public TsysFunctionUserPK() {
    }

    public TsysFunctionUserPK(TsysUser tsysUser, TsysFunction tsysFunction) {
       this.tsysUser = tsysUser;
       this.tsysFunction = tsysFunction;
    }

    public TsysUser getTsysUser() {
        return this.tsysUser;
    }

    public void setTsysUser(TsysUser tsysUser) {
        this.tsysUser = tsysUser;
    }
    public TsysFunction getTsysFunction() {
        return this.tsysFunction;
    }

    public void setTsysFunction(TsysFunction tsysFunction) {
        this.tsysFunction = tsysFunction;
    }
    public boolean equals(Object other) {
        if ( !(other instanceof TsysFunctionUserPK) ) return false;
        TsysFunctionUserPK castOther = (TsysFunctionUserPK) other;
        return new EqualsBuilder()
            .append(this.getTsysFunction().getFunctionid(), castOther.getTsysFunction().getFunctionid())
            .append(this.getTsysUser().getUserid(),  castOther.getTsysUser().getUserid())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getTsysFunction().getFunctionid())
            .append(getTsysUser().getUserid())
            .toHashCode();
    }



}


