package com.sxit.system.model;
// Generated 2007-9-26 16:57:08 by Hibernate Tools 3.2.0.b9



/**
 * TsysPower generated by hbm2java
 */
public class TsysPower  implements java.io.Serializable {


     private short powerid;
     private String powername;
     private int powernum;
     private TsysModule tsysModule;

    public TsysPower() {
    }

    public TsysPower(String powername, int powernum, TsysModule tsysModule) {
       this.powername = powername;
       this.powernum = powernum;
       this.tsysModule = tsysModule;
    }
   
    public short getPowerid() {
        return this.powerid;
    }
    
    public void setPowerid(short powerid) {
        this.powerid = powerid;
    }
    public String getPowername() {
        return this.powername;
    }
    
    public void setPowername(String powername) {
        this.powername = powername;
    }
    public int getPowernum() {
        return this.powernum;
    }
    
    public void setPowernum(int powernum) {
        this.powernum = powernum;
    }
    public TsysModule getTsysModule() {
        return this.tsysModule;
    }
    
    public void setTsysModule(TsysModule tsysModule) {
        this.tsysModule = tsysModule;
    }




}


