
package com.changpeng.models.system;

// Generated 2008-2-21 9:22:49 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TSysUser generated by hbm2java
 * 
 * <pre>
 * 1.加入passkey字段,对输入的password和key进行组合后再md5进行组合
 * </pre>
 */
public class SysUser implements java.io.Serializable {

	private int userid;
	private SysGroup sysGroup;
	private String loginname;
	private String username;
	private String style;
	private String gender;
	private String employeeno;
	private String birthday;
	private String passkey;
	private String password;
	private byte status;
	private String email;
	private boolean delflag;
	private String officephone;
	private String mobile;
	private String comments;
	private String createuser;
	private Timestamp createtime;
	private Set<SysRight> sysRights = new HashSet<SysRight>(0);
	private Set<SysRole> sysRoles = new HashSet<SysRole>(0);
	//同步的时候，同步方的userid;

	private String systemno;
	private String lawerno;
	private String certno;
	private String photo;
	private String zhiyedate;
	
	private String cardno;
	private String carddate;
	
	/**
	 * 用户的角色，1律师，2事务所管理员，3管理员
	 */
	private Integer roleid;

	/**
	 * 绑定这个用户的此次登录的id
	 */
	private int loginId;
    public void setLoginId(int loginId){
    	this.loginId=loginId;
    }
    public int getLoginId(){
    	return this.loginId;
    }
	
	/**
	 * 记录最近一次的登录时间
	 */
	private Timestamp lastLoginTime;
	public void setLastLoginTime(Timestamp lastLoginTime){
		this.lastLoginTime=lastLoginTime;
	}
	public Timestamp getLastLoginTime(){
		return this.lastLoginTime;
	}
	/**
	 * 总计登录次数
	 */
	private int loginCount;
	public void setLoginCount(int loginCount){
		this.loginCount=loginCount;
	}
	public int getLoginCount(){
		return this.loginCount;
	}
	/**
	 * 此人最终的的权限列表
	 */
	private Set<String> rightList;
	public void setRightList(Set<String> rightList){
		this.rightList=rightList;
	}
	public Set<String> getRightList(){
		return this.rightList;
	}
	
	/**
	 * 此人的菜单显示
	 */
	private List<SysRight> userMenus;
	public void setUserMenus(List<SysRight> userMenus){
		this.userMenus=userMenus;
	}
	
	public List<SysRight> getUserMenus(){
		return this.userMenus;
	}
	
	/**
	 * 判断这个人是否有权限
	 * @param rightCode
	 * @return
	 */
	public boolean hasRight(String rightCode){
		if(rightCode==null||rightCode.equals(""))
			return true;
		return rightList.contains(rightCode);
	}
	
	
	public SysUser() {
		
	}

	public SysUser(int userid, String loginname, String password, byte status) {
		this.userid = userid;
		this.loginname = loginname;
		this.password = password;
		this.status = status;
	}

	public SysUser(int userid, SysGroup SysGroup, String loginname, String username, String style, String gender, String employeeno,
			String birthday, String password, byte status, String email, boolean delflag, String officephone, String mobile, String comments,
			String createuser, Timestamp createtime, Set<SysRight> SysRights, Set<SysRole> SysRoles) {
		this.userid = userid;
		this.sysGroup = SysGroup;
		this.loginname = loginname;
		this.username = username;
		this.style = style;
		this.gender = gender;
		this.employeeno = employeeno;
		this.birthday = birthday;
		this.password = password;
		this.status = status;
		this.email = email;
		this.delflag = delflag;
		this.officephone = officephone;
		this.mobile = mobile;
		this.comments = comments;
		this.createuser = createuser;
		this.createtime = createtime;
		this.sysRights = SysRights;
		this.sysRoles = SysRoles;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public SysGroup getSysGroup() {
		return this.sysGroup;
	}

	public void setSysGroup(SysGroup sysGroup) {
		this.sysGroup = sysGroup;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmployeeno() {
		return this.employeeno;
	}

	public void setEmployeeno(String employeeno) {
		this.employeeno = employeeno;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getPasskey() {
		return this.passkey;
	}

	public void setPasskey(String passkey) {
		this.passkey = passkey;
	}
	
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean getDelflag() {
		return this.delflag;
	}

	public void setDelflag(boolean delflag) {
		this.delflag = delflag;
	}

	public String getOfficephone() {
		return this.officephone;
	}

	public void setOfficephone(String officephone) {
		this.officephone = officephone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public Set<SysRight> getSysRights() {
		return this.sysRights;
	}

	public void setSysRights(Set<SysRight> SysRights) {
		this.sysRights = SysRights;
	}

	public Set<SysRole> getSysRoles() {
		return this.sysRoles;
	}

	public void setSysRoles(Set<SysRole> SysRoles) {
		this.sysRoles = SysRoles;
	}
	/**
	 * @return the lwaerno
	 */
	public String getLawerno() {
		return lawerno;
	}
	/**
	 * @param lwaerno the lwaerno to set
	 */
	public void setLawerno(String lwaerno) {
		this.lawerno = lwaerno;
	}
	/**
	 * @return the certno
	 */
	public String getCertno() {
		return certno;
	}
	/**
	 * @param certno the certno to set
	 */
	public void setCertno(String certno) {
		this.certno = certno;
	}
	/**
	 * @return the photo
	 */
	public String getPhoto() {
		return photo;
	}
	/**
	 * @param photo the photo to set
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}
	/**
	 * @return the zhiyedate
	 */
	public String getZhiyedate() {
		return zhiyedate;
	}
	/**
	 * @param zhiyedate the zhiyedate to set
	 */
	public void setZhiyedate(String zhiyedate) {
		this.zhiyedate = zhiyedate;
	}
	/**
	 * @return the cardno
	 */
	public String getCardno() {
		return cardno;
	}
	/**
	 * @param cardno the cardno to set
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno;
	}
	/**
	 * @return the carddate
	 */
	public String getCarddate() {
		return carddate;
	}
	/**
	 * @param carddate the carddate to set
	 */
	public void setCarddate(String carddate) {
		this.carddate = carddate;
	}
	/**
	 * @return the role
	 */
	public Integer getRoleid() {
		return roleid;
	}
	/**
	 * @param role the role to set
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
	/**
	 * @return the systemno
	 */
	public String getSystemno() {
		return systemno;
	}
	/**
	 * @param systemno the systemno to set
	 */
	public void setSystemno(String systemno) {
		this.systemno = systemno;
	}
	
}
