
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;

/**
 * Lessonbaoming generated by hbm2java
 */
public class Lessonbaoming implements java.io.Serializable {

	private int baomingid;
	private Lessons lessons;
	private int userid;
	private Timestamp createtime;

	public Lessonbaoming() {
	}

	public Lessonbaoming(Lessons lessons, int userid, Timestamp createtime) {
		this.lessons = lessons;
		this.userid = userid;
		this.createtime = createtime;
	}

	public int getBaomingid() {
		return this.baomingid;
	}

	public void setBaomingid(int baomingid) {
		this.baomingid = baomingid;
	}

	public Lessons getLessons() {
		return this.lessons;
	}

	public void setLessons(Lessons lessons) {
		this.lessons = lessons;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

}
