
package com.changpeng.models;

// Generated 2008-5-4 12:08:05 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;

/**
 * Lessonscore generated by hbm2java
 */
public class Lessonscore implements java.io.Serializable {

	private int lessonscoreid;
	private Lessons lessons;
	private byte score;
	private int userid;
	private Timestamp scoretime;

	public Lessonscore() {
	}

	public Lessonscore(Lessons lessons, byte score, int userid, Timestamp scoretime) {
		this.lessons = lessons;
		this.score = score;
		this.userid = userid;
		this.scoretime = scoretime;
	}

	public int getLessonscoreid() {
		return this.lessonscoreid;
	}

	public void setLessonscoreid(int lessonid) {
		this.lessonscoreid = lessonid;
	}

	public Lessons getLessons() {
		return this.lessons;
	}

	public void setLessons(Lessons lessons) {
		this.lessons = lessons;
	}

	public byte getScore() {
		return this.score;
	}

	public void setScore(byte score) {
		this.score = score;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Timestamp getScoretime() {
		return this.scoretime;
	}

	public void setScoretime(Timestamp scoretime) {
		this.scoretime = scoretime;
	}

}
