package com.sxit.wait.model;
// Generated 2008-1-11 9:53:21 by Hibernate Tools 3.2.0.b9


import java.sql.Timestamp;

/**
 * TwatInterface generated by hbm2java
 */
public class TwatInteface  implements java.io.Serializable {


     private int intefaceid;
     private String username;
     private String mobile;
     private String bqqno;
     private String email;
     private String content;
     private int statusid;
     private Timestamp createtime;

    public TwatInteface() {
    }


    public TwatInteface(int intefaceid) {
        this.intefaceid = intefaceid;
    }
    public TwatInteface(int intefaceid, String username, String mobile, String bqqno, String email, String content, int statusid, Timestamp createtime) {
       this.intefaceid = intefaceid;
       this.username = username;
       this.mobile = mobile;
       this.bqqno = bqqno;
       this.email = email;
       this.content = content;
       this.statusid = statusid;
       this.createtime = createtime;
    }

    public int getIntefaceid() {
        return this.intefaceid;
    }

    public void setIntefaceid(int intefaceid) {
        this.intefaceid = intefaceid;
    }
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getBqqno() {
        return this.bqqno;
    }

    public void setBqqno(String bqqno) {
        this.bqqno = bqqno;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }
    public int getStatusid() {
        return this.statusid;
    }

    public void setStatusid(int statusid) {
        this.statusid = statusid;
    }
    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }




}


