package com.sxit.wait.model;
// Generated 2007-10-10 17:32:03 by Hibernate Tools 3.2.0.b9


import com.sxit.system.model.TsysUser;
import java.sql.Timestamp;

/**
 * TwatWait generated by hbm2java
 */
public class TwatWait  implements java.io.Serializable {


     private int waitid;
     private String url;
     private String subject;
     private String fromto;
     private int status;
     private String flowstep;
     private int docstatus;
     private Timestamp createtime;
     private String target;
     private TsysUser tsysUser;

    public TwatWait() {
    }

	
    public TwatWait(String url, String subject, String fromto) {
        this.url = url;
        this.subject = subject;
        this.fromto = fromto;
    }
    public TwatWait(String url, String subject, String fromto, int status, String flowstep, int docstatus, Timestamp createtime, String target, TsysUser tsysUser) {
       this.url = url;
       this.subject = subject;
       this.fromto = fromto;
       this.status = status;
       this.flowstep = flowstep;
       this.docstatus = docstatus;
       this.createtime = createtime;
       this.target = target;
       this.tsysUser = tsysUser;
    }
   
    public int getWaitid() {
        return this.waitid;
    }
    
    public void setWaitid(int waitid) {
        this.waitid = waitid;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getFromto() {
        return this.fromto;
    }
    
    public void setFromto(String fromto) {
        this.fromto = fromto;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getFlowstep() {
        return this.flowstep;
    }
    
    public void setFlowstep(String flowstep) {
        this.flowstep = flowstep;
    }
    public int getDocstatus() {
        return this.docstatus;
    }
    
    public void setDocstatus(int docstatus) {
        this.docstatus = docstatus;
    }
    public Timestamp getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }
    public TsysUser getTsysUser() {
        return this.tsysUser;
    }
    
    public void setTsysUser(TsysUser tsysUser) {
        this.tsysUser = tsysUser;
    }




}


