
package com.changpeng.models;

// Generated 2008-5-5 10:58:11 by Hibernate Tools 3.2.0.CR1

/**
 * JifentongjiId generated by hbm2java
 */
public class JifentongjiId implements java.io.Serializable {

	private String lawyername;
	private Integer lawyerid;
	private String groupname;
	private Double xianchang;
	private Double video;
	private Double doc;
	private Double budeng;
	private Double koufen;
	private Double zongjifen;

	public JifentongjiId() {
		
	}

	public JifentongjiId(String groupname) {
		this.groupname = groupname;
	}



	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	public Double getXianchang() {
		return this.xianchang;
	}

	public void setXianchang(Double xianchang) {
		this.xianchang = xianchang;
	}

	public Double getVideo() {
		return this.video;
	}

	public void setVideo(Double video) {
		this.video = video;
	}

	public Double getDoc() {
		return this.doc;
	}

	public void setDoc(Double doc) {
		this.doc = doc;
	}

	public Double getBudeng() {
		return this.budeng;
	}

	public void setBudeng(Double budeng) {
		this.budeng = budeng;
	}

	public Double getKoufen() {
		return this.koufen;
	}

	public void setKoufen(Double koufen) {
		this.koufen = koufen;
	}
	public Double getZongjifen() {
		return Double.parseDouble(com.changpeng.jifen.util.NumberUtil.toMoney(zongjifen+""));
	}


	public void setZongjifen(Double zongjifen) {
		this.zongjifen = zongjifen;
	}

	/**
	 * @return the lawyername
	 */
	public String getLawyername() {
		return lawyername;
	}

	/**
	 * @param lawyername the lawyername to set
	 */
	public void setLawyername(String lawyername) {
		this.lawyername = lawyername;
	}

	/**
	 * @return the lawyerid
	 */
	public Integer getLawyerid() {
		return lawyerid;
	}

	/**
	 * @param lawyerid the lawyerid to set
	 */
	public void setLawyerid(Integer lawyerid) {
		this.lawyerid = lawyerid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JifentongjiId))
			return false;
		JifentongjiId castOther = (JifentongjiId) other;

		return ((this.getLawyername() == castOther.getLawyername()) || (this.getLawyername() != null && castOther.getLawyername() != null && this
				.getLawyername().equals(castOther.getLawyername())))
				&& ((this.getGroupname() == castOther.getGroupname()) || (this.getGroupname() != null && castOther.getGroupname() != null && this
						.getGroupname().equals(castOther.getGroupname())))
				&& ((this.getXianchang() == castOther.getXianchang()) || (this.getXianchang() != null && castOther.getXianchang() != null && this
						.getXianchang().equals(castOther.getXianchang())))
				&& ((this.getVideo() == castOther.getVideo()) || (this.getVideo() != null && castOther.getVideo() != null && this.getVideo().equals(
						castOther.getVideo())))
				&& ((this.getDoc() == castOther.getDoc()) || (this.getDoc() != null && castOther.getDoc() != null && this.getDoc().equals(
						castOther.getDoc())))
				&& ((this.getBudeng() == castOther.getBudeng()) || (this.getBudeng() != null && castOther.getBudeng() != null && this.getBudeng()
						.equals(castOther.getBudeng())))
				&& ((this.getKoufen() == castOther.getKoufen()) || (this.getKoufen() != null && castOther.getKoufen() != null && this.getKoufen()
						.equals(castOther.getKoufen())))
				&& ((this.getZongjifen() == castOther.getZongjifen()) || (this.getZongjifen() != null && castOther.getZongjifen() != null && this
						.getZongjifen().equals(castOther.getZongjifen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLawyername() == null ? 0 : this.getLawyername().hashCode());
		result = 37 * result + (getGroupname() == null ? 0 : this.getGroupname().hashCode());
		result = 37 * result + (getXianchang() == null ? 0 : this.getXianchang().hashCode());
		result = 37 * result + (getVideo() == null ? 0 : this.getVideo().hashCode());
		result = 37 * result + (getDoc() == null ? 0 : this.getDoc().hashCode());
		result = 37 * result + (getBudeng() == null ? 0 : this.getBudeng().hashCode());
		result = 37 * result + (getKoufen() == null ? 0 : this.getKoufen().hashCode());
		result = 37 * result + (getZongjifen() == null ? 0 : this.getZongjifen().hashCode());
		return result;
	}



}
