
package com.sxit.models.system;

// Generated 2008-2-21 9:22:49 by Hibernate Tools 3.2.0.CR1

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TSysRole generated by hbm2java
 */
public class SysRole implements java.io.Serializable {

	private short roleid;
	private String rolename;
//	private String uvisibility;
//	private String gvisibility;
	private String comments;
	private String createuser;
	private Timestamp createtime;
	private Set<SysUser> sysUsers = new HashSet<SysUser>(0);
	private Set<SysRight> sysRights = new HashSet<SysRight>(0);

	private int gradeid; //角色的层级，作为角色a可以分配的角色的判断依据，越小的可分配的角色越多
	public int getGradeid() {
		return gradeid;
	}

	public void setGradeid(int grade) {
		this.gradeid = grade;
	}

	public SysRole() {
	}

	public SysRole(short roleid, String rolename) {
		this.roleid = roleid;
		this.rolename = rolename;
	}

//	public SysRole(short roleid, String rolename, String uvisibility, String gvisibility, String comments, String createuser, Timestamp createtime,
//			Set<SysUser> SysUsers, Set<SysRight> SysRights) {
//		this.roleid = roleid;
//		this.rolename = rolename;
//		this.uvisibility = uvisibility;
//		this.gvisibility = gvisibility;
//		this.comments = comments;
//		this.createuser = createuser;
//		this.createtime = createtime;
//		this.sysUsers = SysUsers;
//		this.sysRights = SysRights;
//	}

	public short getRoleid() {
		return this.roleid;
	}

	public void setRoleid(short roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

//	public String getUvisibility() {
//		return this.uvisibility;
//	}
//
//	public void setUvisibility(String uvisibility) {
//		this.uvisibility = uvisibility;
//	}
//
//	public String getGvisibility() {
//		return this.gvisibility;
//	}
//
//	public void setGvisibility(String gvisibility) {
//		this.gvisibility = gvisibility;
//	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCreateuser() {
		return this.createuser;
	}

	public void setCreateuser(String createuser) {
		this.createuser = createuser;
	}

	public Timestamp getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	public Set<SysUser> getSysUsers() {
		return this.sysUsers;
	}

	public void setSysUsers(Set<SysUser> SysUsers) {
		this.sysUsers = SysUsers;
	}

	public Set<SysRight> getSysRights() {
		return this.sysRights;
	}

	public void setSysRights(Set<SysRight> SysRights) {
		this.sysRights = SysRights;
	}
	
	
	private boolean datavisible; //是否设置数据可见性,默认false
	private String visiblefield ;//设置可见性的话,哪些个字段
	private boolean recursion;  //是否递归,也就是是否可以到子的部分
	
	public boolean getRecursion() {
		return recursion;
	}

	public void setRecursion(boolean recursion) {
		this.recursion = recursion;
	}

	public boolean getDatavisible() {
		return datavisible;
	}

	public void setDatavisible(boolean datavisible) {
		this.datavisible = datavisible;
	}

	public String getVisiblefield() {
		return visiblefield;
	}

	public void setVisiblefield(String visiblefield) {
		this.visiblefield = visiblefield;
	}
}
