package com.sxit.member.model;
// Generated 2008-5-28 10:53:41 by Hibernate Tools 3.2.0.b9



/**
 * TmemSkill generated by hbm2java
 */
public class TmemSkill  implements java.io.Serializable {


     private int skillid;
     private TmemResume tmemResume;
     private String skillname;
     private String degree;
     private String description;
     private Long years;

    public TmemSkill() {
    }

    public TmemSkill(TmemResume tmemResume, String skillname, String degree, String description, Long years) {
       this.tmemResume = tmemResume;
       this.skillname = skillname;
       this.degree = degree;
       this.description = description;
       this.years = years;
    }
   
    public int getSkillid() {
        return this.skillid;
    }
    
    public void setSkillid(int skillid) {
        this.skillid = skillid;
    }
    public TmemResume getTmemResume() {
        return this.tmemResume;
    }
    
    public void setTmemResume(TmemResume tmemResume) {
        this.tmemResume = tmemResume;
    }
    public String getSkillname() {
        return this.skillname;
    }
    
    public void setSkillname(String skillname) {
        this.skillname = skillname;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Long getYears() {
        return this.years;
    }
    
    public void setYears(Long years) {
        this.years = years;
    }




}


