package com.sxit.member.model;
// Generated 2008-5-28 10:53:41 by Hibernate Tools 3.2.0.b9


import java.sql.Timestamp;

/**
 * TmemWorkexp generated by hbm2java
 */
public class TmemWorkexp  implements java.io.Serializable {


     private int workexpid;
     private TmemResume tmemResume;
     private String companyname;
     private String character;
     private String duty;
     private Timestamp begindate;
     private Timestamp enddate;
     private Long salary;
     private String leavereason;
     private String achievement;
     private String attesterman;
     private String attestermanduty;
     private String attestermanphone;

    public TmemWorkexp() {
    }

    public TmemWorkexp(TmemResume tmemResume, String companyname, String character, String duty, Timestamp begindate, Timestamp enddate, Long salary, String leavereason, String achievement, String attesterman, String attestermanduty, String attestermanphone) {
       this.tmemResume = tmemResume;
       this.companyname = companyname;
       this.character = character;
       this.duty = duty;
       this.begindate = begindate;
       this.enddate = enddate;
       this.salary = salary;
       this.leavereason = leavereason;
       this.achievement = achievement;
       this.attesterman = attesterman;
       this.attestermanduty = attestermanduty;
       this.attestermanphone = attestermanphone;
    }
   
    public int getWorkexpid() {
        return this.workexpid;
    }
    
    public void setWorkexpid(int workexpid) {
        this.workexpid = workexpid;
    }
    public TmemResume getTmemResume() {
        return this.tmemResume;
    }
    
    public void setTmemResume(TmemResume tmemResume) {
        this.tmemResume = tmemResume;
    }
    public String getCompanyname() {
        return this.companyname;
    }
    
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
    public String getCharacter() {
        return this.character;
    }
    
    public void setCharacter(String character) {
        this.character = character;
    }
    public String getDuty() {
        return this.duty;
    }
    
    public void setDuty(String duty) {
        this.duty = duty;
    }
    public Timestamp getBegindate() {
        return this.begindate;
    }
    
    public void setBegindate(Timestamp begindate) {
        this.begindate = begindate;
    }
    public Timestamp getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Timestamp enddate) {
        this.enddate = enddate;
    }
    public Long getSalary() {
        return this.salary;
    }
    
    public void setSalary(Long salary) {
        this.salary = salary;
    }
    public String getLeavereason() {
        return this.leavereason;
    }
    
    public void setLeavereason(String leavereason) {
        this.leavereason = leavereason;
    }
    public String getAchievement() {
        return this.achievement;
    }
    
    public void setAchievement(String achievement) {
        this.achievement = achievement;
    }
    public String getAttesterman() {
        return this.attesterman;
    }
    
    public void setAttesterman(String attesterman) {
        this.attesterman = attesterman;
    }
    public String getAttestermanduty() {
        return this.attestermanduty;
    }
    
    public void setAttestermanduty(String attestermanduty) {
        this.attestermanduty = attestermanduty;
    }
    public String getAttestermanphone() {
        return this.attestermanphone;
    }
    
    public void setAttestermanphone(String attestermanphone) {
        this.attestermanphone = attestermanphone;
    }




}


